# Specify processor and model
processor_name: google/owlv2-large-patch14-finetuned
model_name: google/owlv2-large-patch14-finetuned

threshold: 0.3

# File paths
data_folder: data # Not used
filepath: data/tower3.jpg
save_output: True # Not used
output_folder: output # Not used