# Specify processor and model
processor_name: google/owlv2-large-patch14-finetuned
model_name: google/owlv2-large-patch14-finetuned

threshold: 0.2

# File paths
data_folder: data
save_output: True
output_folder: output